version: v1
plugins:
  - plugin: swagger
    out: ../docs/static
    opt:
      - allow_merge=true
      - merge_file_name=swagger.json
      - logtostderr=true
      - fqn_for_swagger_name=true
      - simple_operation_ids=true
